"""Goldens for the per-tablet Isabelle session SCAFFOLD generator (B2d).

Asserts the generated ``ROOT`` + ``Tablet_Preamble.thy`` byte-match a golden
for a 2-node fixture tablet, the session-qualified theory naming
(``Tablet_<Node>``, never a global name), the ROOT ``options`` block
(``quick_and_dirty = false``; ``record_proofs = 0``; NO ``proofs = 1``), the
sorted/deterministic theory list, the fail-closed stub for an absent node,
and the ``sync_session`` writer end-to-end (including that it derives the node
set from the present worker ``Tablet_<Node>.thy`` files and never rewrites a
worker body). Also exercises the ``isabelle_sync_session`` /
``isabelle_build_session`` server handlers (scaffold written under the
socket-derived repo; build is a no-op-success with no ROOT).
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Iterator

import pytest

from trellis.checker import isabelle_scaffold as scaffold
from trellis.checker.protocol import CheckerRequest
from trellis.checker.server import CheckerServer


# ============================ pure render goldens ============================

# The golden ROOT for a 2-node tablet {Alpha, Beta} (+ the always-present
# Tablet_Preamble base). Pinned byte-for-byte: the session-qualified names,
# the options block (quick_and_dirty=false, bounded threads/parallel_proofs/
# timeout, NO proofs=1), Preamble listed first, nodes sorted.
GOLDEN_ROOT_TWO_NODE = """\
(* Auto-generated by .trellis. Do not edit. *)
session Tablet_Base in "base" = "HOL-Probability" +
  options [record_proofs = 0, threads = 2, parallel_proofs = 1, timeout = 1800]

session Tablet = Tablet_Base +
  options [record_proofs = 0, threads = 2, parallel_proofs = 1, timeout = 1800]
  theories
    Tablet_Preamble
    Tablet_Alpha
    Tablet_Beta
"""

GOLDEN_PREAMBLE = """\
theory Tablet_Preamble
  imports Complex_Main
begin

end
"""


def test_golden_root_two_node() -> None:
    text = scaffold.generate_root(["Tablet_Alpha", "Tablet_Beta"])
    assert text == GOLDEN_ROOT_TWO_NODE


def test_golden_preamble() -> None:
    assert scaffold.generate_preamble_thy() == GOLDEN_PREAMBLE


def test_root_options_quick_and_dirty_false_and_no_proofs_option() -> None:
    """The soundness-relevant ROOT policy: quick_and_dirty=false (a stray
    sorry FAILS the build), ``record_proofs = 0`` for oracle attribution, and NO ``proofs`` option
    (invalid in 2025-2; oracle names record at level 0 regardless)."""
    text = scaffold.generate_root(["Tablet_Alpha"])
    # `quick_and_dirty` is deliberately NOT pinned in ROOT. Session options
    # OVERRIDE a command-line `-o`, so pinning it made the policy un-selectable
    # per invocation — and pinning it FALSE made a single open node fail the
    # whole-session materialization build, contradicting the phase contract that
    # a node may be OPEN with its proof deferred. Isabelle's global default is
    # already `false`, so STRICT remains the default; materialization opts into
    # `quick_and_dirty=true` explicitly and the completion gate keeps the default.
    assert "quick_and_dirty" not in text
    # The stale option is a BARE ``proofs`` key; ``parallel_proofs`` is a
    # different, valid option, so match the bare key with a leading delimiter.
    assert "[proofs = " not in text and ", proofs = " not in text
    # `record_proofs = 0` is REQUIRED (it used to be wrongly excluded). Level 0
    # retains the theorem dependency boxes and oracle names the checker's cut
    # traversal needs to attribute an oracle to the proof that introduced it —
    # i.e. to tell a node's own `sorry` apart from a declared child's. It does
    # NOT record explicit proof terms (level 2), which would be costly and would
    # not reuse the prebuilt HOL heap. `proofs = 1` really is not a valid option
    # name; `record_proofs` is (`etc/options`).
    assert "record_proofs = 0" in text
    # The working session parents on the warm base; the base parents on
    # HOL-Probability. Both stanzas land in the one ROOT. The hyphenated parent
    # MUST be double-quoted (it is not a bare long-ident, so an unquoted
    # ``= HOL-Probability +`` fails the ROOT parse), and the base stanza MUST
    # carry an ``in "<subdir>"`` so it does not share the ROOT dir with
    # ``Tablet`` (``Duplicate use of directory`` otherwise).
    assert "session Tablet = Tablet_Base +" in text
    assert 'session Tablet_Base in "base" = "HOL-Probability" +' in text
    # The bare unquoted form (the pre-fix bug) must NOT appear.
    assert "= HOL-Probability +" not in text


def test_base_session_name_quoted_only_when_needed() -> None:
    """``_quote_session_name`` quotes a hyphenated/symbolic session name but
    leaves a bare long-ident (``HOL``, ``Tablet_Base``) unquoted."""
    assert scaffold._quote_session_name("HOL-Probability") == '"HOL-Probability"'
    assert scaffold._quote_session_name("HOL") == "HOL"
    assert scaffold._quote_session_name("Tablet_Base") == "Tablet_Base"


def test_sync_session_creates_base_subdir(tmp_path: Path) -> None:
    """The base stanza declares ``in "base"``; ``sync_session`` must create that
    (empty) subdir on disk or ``isabelle build`` fails ``No such directory``."""
    session_dir = tmp_path / "isabelle"
    scaffold.sync_session(session_dir)
    base_dir = session_dir / scaffold.BASE_SESSION_DIR
    assert base_dir.is_dir()


def test_node_theory_names_are_session_qualified() -> None:
    """Theory names are ``Tablet_<Node>`` (session-qualified), never a bare
    global name like ``Alpha`` (research 02 R5 — regular sessions must not
    claim global theory names)."""
    assert scaffold.node_theory_name("Alpha") == "Tablet_Alpha"
    render = scaffold.render_scaffold(["Alpha", "Beta"])
    assert list(render.node_theories) == ["Tablet_Alpha", "Tablet_Beta"]
    for theory in render.node_theories:
        assert theory.startswith("Tablet_")


def test_render_is_sorted_and_deterministic() -> None:
    """The node theory list is sorted (BTreeSet parity with the Lean umbrella)
    so the ROOT is byte-stable regardless of input order."""
    a = scaffold.render_scaffold(["Beta", "Alpha", "Gamma"])
    b = scaffold.render_scaffold(["Gamma", "Alpha", "Beta"])
    assert a.root_text == b.root_text
    assert list(a.node_theories) == ["Tablet_Alpha", "Tablet_Beta", "Tablet_Gamma"]


def test_preamble_pseudo_node_is_dropped_from_node_list() -> None:
    """A ``Preamble`` stem maps to the generated ``Tablet_Preamble`` base and
    is never emitted as a node theory (it is listed once, first, in ROOT)."""
    render = scaffold.render_scaffold(["Preamble", "Alpha"])
    assert list(render.node_theories) == ["Tablet_Alpha"]
    # Preamble appears exactly once in ROOT (the generated base line).
    assert render.root_text.count("Tablet_Preamble") == 1


def test_invalid_node_name_rejected() -> None:
    for bad in ["1bad", "has-dash", "has space", "", "a.b"]:
        with pytest.raises(ValueError):
            scaffold.render_scaffold([bad])


def test_absent_node_gets_fail_closed_stub_and_is_listed() -> None:
    """A registered node whose worker ``.thy`` is absent gets a fail-closed
    stub (an ``oops``'d ``False`` goal — the build FAILS, never silently
    drops the node) and is still listed in ROOT."""
    render = scaffold.render_scaffold(
        ["Alpha"], absent_node_stems=["Ghost"]
    )
    assert "Tablet_Ghost" in render.node_theories
    stub = render.node_stub_texts["Tablet_Ghost"]
    assert "theory Tablet_Ghost" in stub
    assert "imports Tablet_Preamble" in stub
    assert "lemma Ghost: False" in stub
    assert "oops" in stub
    # No ``sorry`` (which under quick_and_dirty=false would still fail, but the
    # intent is an unprovable, unfinished goal).
    assert "sorry" not in stub


# ============================ sync_session writer ============================


def test_sync_session_writes_root_and_preamble(tmp_path: Path) -> None:
    """End-to-end: two worker node theories present on disk ⇒ ROOT lists both
    (sorted) + Preamble, and the worker bodies are left UNTOUCHED."""
    session_dir = tmp_path / "isabelle"
    session_dir.mkdir()
    # Worker-authored complete node theories (the Tablet/<Node>.lean analogue).
    alpha_body = (
        "theory Tablet_Alpha\n  imports Tablet_Preamble\nbegin\n\n"
        'lemma Alpha: "(1::nat)+1=2" by simp\n\nend\n'
    )
    beta_body = (
        "theory Tablet_Beta\n  imports Tablet_Preamble Tablet_Alpha\nbegin\n\n"
        'lemma Beta: "(2::nat)+0=2" by simp\n\nend\n'
    )
    (session_dir / "Tablet_Alpha.thy").write_text(alpha_body, encoding="utf-8")
    (session_dir / "Tablet_Beta.thy").write_text(beta_body, encoding="utf-8")

    summary = scaffold.sync_session(session_dir)

    assert (session_dir / "ROOT").read_text(encoding="utf-8") == GOLDEN_ROOT_TWO_NODE
    assert (session_dir / "Tablet_Preamble.thy").read_text(
        encoding="utf-8"
    ) == GOLDEN_PREAMBLE
    # Worker bodies are NOT rewritten by the generator.
    assert (session_dir / "Tablet_Alpha.thy").read_text(encoding="utf-8") == alpha_body
    assert (session_dir / "Tablet_Beta.thy").read_text(encoding="utf-8") == beta_body
    assert summary["node_theories"] == ["Tablet_Alpha", "Tablet_Beta"]


def test_sync_session_empty_dir_writes_preamble_only_root(tmp_path: Path) -> None:
    session_dir = tmp_path / "isabelle"
    summary = scaffold.sync_session(session_dir)
    root = (session_dir / "ROOT").read_text(encoding="utf-8")
    assert "Tablet_Preamble" in root
    # No node theories listed beyond the Preamble base.
    assert summary["node_theories"] == []
    assert (session_dir / "Tablet_Preamble.thy").is_file()


def test_sync_session_absent_expected_node_writes_stub(tmp_path: Path) -> None:
    """When the caller registers an expected node set, an expected node with no
    worker ``.thy`` on disk gets a fail-closed stub file written."""
    session_dir = tmp_path / "isabelle"
    session_dir.mkdir()
    (session_dir / "Tablet_Alpha.thy").write_text(
        "theory Tablet_Alpha\n  imports Tablet_Preamble\nbegin\nend\n",
        encoding="utf-8",
    )
    summary = scaffold.sync_session(session_dir, node_stems=["Alpha", "Ghost"])
    assert (session_dir / "Tablet_Ghost.thy").is_file()
    stub = (session_dir / "Tablet_Ghost.thy").read_text(encoding="utf-8")
    assert "oops" in stub
    assert "Tablet_Ghost" in summary["node_theories"]
    assert "Tablet_Alpha" in summary["node_theories"]


def test_sync_session_ignores_stray_non_node_thy(tmp_path: Path) -> None:
    """A stray ``.thy`` that is not a ``Tablet_<Node>`` file is ignored, not
    fatal (robust to a dirty session dir)."""
    session_dir = tmp_path / "isabelle"
    session_dir.mkdir()
    (session_dir / "Tablet_Alpha.thy").write_text(
        "theory Tablet_Alpha\n  imports Tablet_Preamble\nbegin\nend\n",
        encoding="utf-8",
    )
    # A loose, non-conforming theory file.
    (session_dir / "Scratch.thy").write_text("theory Scratch begin end\n", encoding="utf-8")
    summary = scaffold.sync_session(session_dir)
    assert summary["node_theories"] == ["Tablet_Alpha"]


# ===================== worker Tablet/ -> session projection =====================


def _make_supervisor_layout(tmp_path: Path) -> tuple[Path, Path]:
    """A supervisor-repo-shaped layout: ``<repo>/Tablet/`` (worker mirror) and
    ``<repo>/isabelle/`` (the session dir). Returns ``(session_dir, tablet_dir)``.
    ``session_dir.parent / "Tablet"`` is the projection source, mirroring the
    production ``session_dir == <supervisor_repo>/isabelle`` relationship."""
    repo = tmp_path / "supervisor"
    session_dir = repo / "isabelle"
    tablet_dir = repo / "Tablet"
    session_dir.mkdir(parents=True)
    tablet_dir.mkdir(parents=True)
    return session_dir, tablet_dir


def test_sync_session_projects_worker_tablet_thy_into_session(tmp_path: Path) -> None:
    """A worker ``Tablet/Foo.thy`` (header ``theory Tablet_Foo``) is projected
    to ``isabelle/Tablet_Foo.thy`` byte-for-byte and listed in the rendered
    ROOT as a real node theory (not a fail-closed stub)."""
    session_dir, tablet_dir = _make_supervisor_layout(tmp_path)
    foo_body = (
        "theory Tablet_Foo\n  imports Tablet_Preamble\nbegin\n\n"
        'lemma Foo: "(1::nat)+1=2" by simp\n\nend\n'
    )
    (tablet_dir / "Foo.thy").write_text(foo_body, encoding="utf-8")

    summary = scaffold.sync_session(session_dir)

    projected = session_dir / "Tablet_Foo.thy"
    assert projected.is_file()
    # Body + header byte-untouched (pure copy+rename of the stem).
    assert projected.read_text(encoding="utf-8") == foo_body
    assert summary["node_theories"] == ["Tablet_Foo"]
    root = (session_dir / "ROOT").read_text(encoding="utf-8")
    assert "Tablet_Foo" in root
    # It is the real worker theory, not the fail-closed stub.
    assert "oops" not in projected.read_text(encoding="utf-8")


def test_sync_session_stale_sweep_removes_projection_when_source_dropped(
    tmp_path: Path,
) -> None:
    """Deleting the worker source ``Tablet/Foo.thy`` removes the projected
    ``isabelle/Tablet_Foo.thy`` on the next ``sync_session`` (mirrors
    ``sync_tablet_dir``'s removal sweep) so a dropped node leaves no ghost."""
    session_dir, tablet_dir = _make_supervisor_layout(tmp_path)
    (tablet_dir / "Foo.thy").write_text(
        "theory Tablet_Foo\n  imports Tablet_Preamble\nbegin\nend\n",
        encoding="utf-8",
    )
    scaffold.sync_session(session_dir)
    assert (session_dir / "Tablet_Foo.thy").is_file()

    (tablet_dir / "Foo.thy").unlink()
    summary = scaffold.sync_session(session_dir)

    assert not (session_dir / "Tablet_Foo.thy").exists()
    assert summary["node_theories"] == []
    root = (session_dir / "ROOT").read_text(encoding="utf-8")
    assert "Tablet_Foo" not in root


def test_h3_cert_probe_stem_never_enumerated_as_node(tmp_path: Path) -> None:
    """H3: a ``Tablet_<Node>__Cert.thy`` probe stem is NEVER enumerated as a
    node, even though ``<Node>__Cert`` matches the node-name regex. So a probe
    that outlived its sweep cannot be pulled into the cold build's ROOT or the
    warm prefix."""
    session_dir = tmp_path / "isabelle"
    session_dir.mkdir()
    (session_dir / "Tablet_Foo.thy").write_text(
        "theory Tablet_Foo\n  imports Tablet_Preamble\nbegin\nend\n", encoding="utf-8"
    )
    # A leftover checker probe theory (no worker source dir, so the sweep does
    # not run): it must still be excluded from node enumeration.
    (session_dir / "Tablet_Foo__Cert.thy").write_text(
        "theory Tablet_Foo__Cert\n  imports Tablet_Foo\nbegin\nend\n", encoding="utf-8"
    )
    assert scaffold._node_stems_in_session_dir(session_dir) == ["Foo"]
    summary = scaffold.sync_session(session_dir)
    assert summary["node_theories"] == ["Tablet_Foo"]
    root = (session_dir / "ROOT").read_text(encoding="utf-8")
    assert "Tablet_Foo__Cert" not in root


def test_h3_cert_probe_swept_when_source_dir_present(tmp_path: Path) -> None:
    """H3: with a worker ``Tablet/`` source dir present, the projection sweep
    DELETES a stray ``Tablet_<Node>__Cert.thy`` probe (it has no worker source
    and is never a persistent file)."""
    session_dir, tablet_dir = _make_supervisor_layout(tmp_path)
    (tablet_dir / "Foo.thy").write_text(
        "theory Tablet_Foo\n  imports Tablet_Preamble\nbegin\nend\n", encoding="utf-8"
    )
    # Pre-seed a leftover probe in the session dir.
    (session_dir / "Tablet_Foo__Cert.thy").write_text(
        "theory Tablet_Foo__Cert\n  imports Tablet_Foo\nbegin\nend\n", encoding="utf-8"
    )
    summary = scaffold.sync_session(session_dir)
    # The probe was swept; only the real node theory remains.
    assert not (session_dir / "Tablet_Foo__Cert.thy").exists()
    assert summary["node_theories"] == ["Tablet_Foo"]


def test_sync_session_does_not_project_preamble_as_node(tmp_path: Path) -> None:
    """A worker ``Tablet/Preamble.thy`` is NOT projected as a node theory — the
    session base is the GENERATED ``Tablet_Preamble.thy`` (its imports DERIVED
    from the worker preamble, its body generator-owned). So the session dir
    gets no byte-for-byte ``Tablet_Preamble`` from the worker source, and
    Preamble never appears as a node in the ROOT (only the generated base
    line)."""
    session_dir, tablet_dir = _make_supervisor_layout(tmp_path)
    # A worker-side Preamble.thy alongside a real node.
    worker_preamble = "theory Tablet_Preamble\n  imports Main\nbegin\nend\n"
    (tablet_dir / "Preamble.thy").write_text(worker_preamble, encoding="utf-8")
    (tablet_dir / "Foo.thy").write_text(
        "theory Tablet_Foo\n  imports Tablet_Preamble\nbegin\nend\n",
        encoding="utf-8",
    )

    summary = scaffold.sync_session(session_dir)

    assert summary["node_theories"] == ["Tablet_Foo"]
    # The generated Preamble is present + byte-equals the generator's DERIVED
    # output (imports adopted from the worker preamble, body generator-owned)
    # — i.e. it was NOT overwritten by a worker Preamble.thy projection.
    generated = (session_dir / "Tablet_Preamble.thy").read_text(encoding="utf-8")
    assert generated == scaffold.generate_preamble_thy(["Main"])
    assert generated != worker_preamble
    root = (session_dir / "ROOT").read_text(encoding="utf-8")
    # Preamble appears exactly once (the generated base line), never as a node.
    assert root.count("Tablet_Preamble") == 1


# ================ worker preamble -> derived session preamble ================


# Byte-level golden for the DERIVED session preamble when the worker's
# ``Tablet/Preamble.thy`` imports the probability library (the live run's
# actual worker preamble shape). The header comment states the source; the
# hyphenated session-qualified name is double-quoted (its only legal
# spelling).
GOLDEN_DERIVED_PREAMBLE_PROBABILITY = """\
(* Auto-generated by .trellis; imports derived from Tablet/Preamble.thy. Do not edit. *)
theory Tablet_Preamble
  imports "HOL-Probability.Probability"
begin

end
"""


def test_sync_session_derives_preamble_imports_from_worker_preamble(
    tmp_path: Path,
) -> None:
    """A worker ``Tablet/Preamble.thy`` importing ``"HOL-Probability.
    Probability"`` (allowlisted; the live wedge) is honored: the generated
    session preamble carries that import, byte-for-byte against the golden,
    with the header comment stating the source."""
    session_dir, tablet_dir = _make_supervisor_layout(tmp_path)
    (tablet_dir / "Preamble.thy").write_text(
        'theory Tablet_Preamble\n  imports "HOL-Probability.Probability"\n'
        "begin\n\nend\n",
        encoding="utf-8",
    )

    summary = scaffold.sync_session(session_dir)

    text = (session_dir / "Tablet_Preamble.thy").read_text(encoding="utf-8")
    assert text == GOLDEN_DERIVED_PREAMBLE_PROBABILITY
    assert "derived from Tablet/Preamble.thy" in text
    assert summary["preamble_derived"] is True
    assert summary["preamble_imports"] == ["HOL-Probability.Probability"]


def test_sync_session_preamble_falls_back_on_disallowed_import(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """A worker preamble import off the allowlist abandons the WHOLE
    derivation: the generated preamble is the historical fallback constant
    (never fail-open into a broader environment) and the fallback is loudly
    logged."""
    session_dir, tablet_dir = _make_supervisor_layout(tmp_path)
    (tablet_dir / "Preamble.thy").write_text(
        'theory Tablet_Preamble\n  imports Main "HOL-Library.Foo"\nbegin\nend\n',
        encoding="utf-8",
    )

    with caplog.at_level("WARNING", logger="trellis.checker.isabelle_scaffold"):
        summary = scaffold.sync_session(session_dir)

    assert (session_dir / "Tablet_Preamble.thy").read_text(
        encoding="utf-8"
    ) == GOLDEN_PREAMBLE
    assert summary["preamble_derived"] is False
    assert summary["preamble_imports"] == [scaffold.PREAMBLE_IMPORTS]
    assert any(
        record.levelname == "ERROR"
        and "falls back to the historical constant" in record.getMessage()
        and "HOL-Library.Foo" in record.getMessage()
        for record in caplog.records
    ), f"the fallback must be loudly logged: {caplog.text}"


def test_sync_session_preamble_falls_back_on_tablet_import(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """A ``Tablet_*`` import in the worker preamble is forbidden (the preamble
    IS the import root) ⇒ fallback + loud log."""
    session_dir, tablet_dir = _make_supervisor_layout(tmp_path)
    (tablet_dir / "Preamble.thy").write_text(
        "theory Tablet_Preamble\n  imports Complex_Main Tablet_Foo\nbegin\nend\n",
        encoding="utf-8",
    )

    with caplog.at_level("WARNING", logger="trellis.checker.isabelle_scaffold"):
        summary = scaffold.sync_session(session_dir)

    assert (session_dir / "Tablet_Preamble.thy").read_text(
        encoding="utf-8"
    ) == GOLDEN_PREAMBLE
    assert summary["preamble_derived"] is False
    assert any(
        record.levelname == "ERROR" and "Tablet" in record.getMessage()
        for record in caplog.records
    ), f"the Tablet-import fallback must be loudly logged: {caplog.text}"


def test_sync_session_preamble_falls_back_on_absent_worker_preamble(
    tmp_path: Path,
) -> None:
    """No worker ``Tablet/Preamble.thy`` ⇒ the generated preamble is the
    historical fallback constant, byte-identical (fresh repos / fixtures)."""
    session_dir, tablet_dir = _make_supervisor_layout(tmp_path)
    (tablet_dir / "Foo.thy").write_text(
        "theory Tablet_Foo\n  imports Tablet_Preamble\nbegin\nend\n",
        encoding="utf-8",
    )
    summary = scaffold.sync_session(session_dir)
    assert (session_dir / "Tablet_Preamble.thy").read_text(
        encoding="utf-8"
    ) == GOLDEN_PREAMBLE
    assert summary["preamble_derived"] is False


def test_sync_session_preamble_falls_back_on_unparseable_clause(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """An imports clause the strict parser cannot read (comment / cartouche /
    escape junk) ⇒ fallback + loud log — never a guess."""
    session_dir, tablet_dir = _make_supervisor_layout(tmp_path)
    (tablet_dir / "Preamble.thy").write_text(
        "theory Tablet_Preamble\n  imports Main (* sneaky *)\nbegin\nend\n",
        encoding="utf-8",
    )

    with caplog.at_level("WARNING", logger="trellis.checker.isabelle_scaffold"):
        summary = scaffold.sync_session(session_dir)

    assert (session_dir / "Tablet_Preamble.thy").read_text(
        encoding="utf-8"
    ) == GOLDEN_PREAMBLE
    assert summary["preamble_derived"] is False
    assert any(
        record.levelname == "ERROR"
        and "no parseable imports clause" in record.getMessage()
        for record in caplog.records
    ), f"the unparseable fallback must be loudly logged: {caplog.text}"


def test_derive_preamble_imports_mixed_spellings_dedup_and_rendering(
    tmp_path: Path,
) -> None:
    """Bare + quoted allowlisted imports are adopted in source order with
    duplicates dropped; rendering re-quotes ONLY the names that are not bare
    long-idents (the hyphenated session-qualified ones)."""
    preamble = tmp_path / "Preamble.thy"
    preamble.write_text(
        "theory Tablet_Preamble\n"
        '  imports Complex_Main "HOL-Probability.Probability" HOL.List\n'
        "    Complex_Main\n"
        "begin\nend\n",
        encoding="utf-8",
    )
    derived = scaffold.derive_preamble_imports(preamble)
    assert derived == [
        "Complex_Main",
        "HOL-Probability.Probability",
        "HOL.List",
    ]
    text = scaffold.generate_preamble_thy(derived)
    assert (
        '  imports Complex_Main "HOL-Probability.Probability" HOL.List\n' in text
    )


def test_generate_preamble_thy_fallback_is_byte_identical_to_historical() -> None:
    """The no-argument (fallback) render is the historical constant body,
    byte-for-byte — pre-derivation scaffold bytes (and thus cert-cache keys)
    are reproduced exactly whenever the fallback is in effect."""
    assert scaffold.generate_preamble_thy() == GOLDEN_PREAMBLE
    assert scaffold.generate_preamble_thy(None) == GOLDEN_PREAMBLE


# ============================ server handler wiring ============================


@pytest.fixture
def runtime_root() -> Iterator[Path]:
    base = Path(tempfile.mkdtemp(prefix="isa-scaffold-", dir="/tmp"))
    repo = base / "r"
    runtime = repo / ".trellis" / "runtime" / "rt"
    runtime.mkdir(parents=True)
    (repo / "Tablet").mkdir(parents=True)
    yield runtime
    import shutil

    shutil.rmtree(base, ignore_errors=True)


def test_handler_sync_session_writes_scaffold_under_socket_repo(
    runtime_root: Path,
) -> None:
    """``isabelle_sync_session`` writes the scaffold into the socket-derived
    ``<supervisor_repo>/isabelle/`` dir — never a request-supplied path."""
    server = CheckerServer(runtime_root, parallelism=1, socket_group_gid=None)
    server.set_expected_peer_uid(os.geteuid())
    session_dir = server.supervisor_repo / "isabelle"
    session_dir.mkdir(parents=True, exist_ok=True)
    (session_dir / "Tablet_Alpha.thy").write_text(
        "theory Tablet_Alpha\n  imports Tablet_Preamble\nbegin\nend\n",
        encoding="utf-8",
    )

    req = CheckerRequest(op="isabelle_sync_session", request_id=1, timeout_secs=60.0)
    response, rc, log_extra = server._handle_isabelle_workspace_op(req)

    assert rc == 0
    assert response["returncode"] == 0
    summary = json.loads(response["stdout"])
    assert summary["node_theories"] == ["Tablet_Alpha"]
    assert (session_dir / "ROOT").is_file()
    assert (session_dir / "Tablet_Preamble.thy").is_file()
    # The path the handler used is under the socket-derived supervisor repo.
    assert str(server.supervisor_repo) in log_extra["isabelle_session_dir"]


def test_handler_build_session_noop_success_without_root(
    runtime_root: Path,
) -> None:
    """``isabelle_build_session`` is a no-op-success when no scaffold ROOT
    exists (the production state — no IsabelleHol tablet live), so the
    kernel's precondition path is satisfied without spawning ``isabelle``."""
    server = CheckerServer(runtime_root, parallelism=1, socket_group_gid=None)
    server.set_expected_peer_uid(os.geteuid())

    req = CheckerRequest(op="isabelle_build_session", request_id=2, timeout_secs=60.0)
    response, rc, _ = server._handle_isabelle_workspace_op(req)
    assert rc == 0
    assert response["returncode"] == 0


def test_allowlist_replica_stays_in_lockstep_with_the_rust_constant() -> None:
    """D2 — the Python replica must equal `ISABELLE_HOL_ALLOWED_IMPORT_PREFIXES`.

    The replica gates the SESSION IMPORT ROOT. If it drifts wider than the Rust
    constant that gates worker imports, the root admits sessions the worker gate
    rejects; narrower, and a legal worker preamble silently falls back.
    """
    import re
    from pathlib import Path

    from trellis.checker.isabelle_scaffold import ALLOWED_PREAMBLE_IMPORT_PREFIXES

    backend_rs = (
        Path(__file__).resolve().parents[1] / "kernel" / "src" / "backend.rs"
    ).read_text(encoding="utf-8")
    block = re.search(
        r"ISABELLE_HOL_ALLOWED_IMPORT_PREFIXES:\s*&\[&str\]\s*=\s*&\[(.*?)\];",
        backend_rs,
        re.S,
    )
    assert block, "could not locate the Rust allowlist constant"
    rust = tuple(re.findall(r'"([^"]+)"', block.group(1)))
    assert tuple(ALLOWED_PREAMBLE_IMPORT_PREFIXES) == rust, (
        f"allowlist drift: python={tuple(ALLOWED_PREAMBLE_IMPORT_PREFIXES)} rust={rust}"
    )


def _derived_session(tmp_path, imports_line: str):
    """A session dir whose generated preamble is a DERIVED render."""
    from trellis.checker.isabelle_scaffold import sync_session

    (tmp_path / "Tablet").mkdir(parents=True, exist_ok=True)
    (tmp_path / "Tablet" / "Preamble.thy").write_text(
        f"theory Tablet_Preamble\n  imports {imports_line}\nbegin\n\nend\n",
        encoding="utf-8",
    )
    session = tmp_path / "isabelle"
    session.mkdir(exist_ok=True)
    sync_session(session)
    return session


def test_derived_preamble_is_sticky_against_a_failed_derivation(tmp_path) -> None:
    """D1 — a derivation failure must not silently narrow the import root.

    Once the session preamble is derived, falling back to `Complex_Main`
    re-elaborates every node in a different theory context: cert-cache keys mass-
    invalidate, and a node accepted in that window pins its approved corr
    fingerprint from narrow-env prints.
    """
    import pytest

    from trellis.checker.isabelle_scaffold import (
        DERIVED_PREAMBLE_MARKER,
        PREAMBLE_ALLOW_FALLBACK_ENV,
        sync_session,
    )

    session = _derived_session(tmp_path, '"HOL-Probability.Probability"')
    preamble = session / "Tablet_Preamble.thy"
    derived_bytes = preamble.read_bytes()
    assert DERIVED_PREAMBLE_MARKER in derived_bytes.decode()

    # Break the worker preamble (a torn read / bad edit).
    (tmp_path / "Tablet" / "Preamble.thy").write_text("garbage", encoding="utf-8")

    with pytest.raises(RuntimeError, match="DERIVED render"):
        sync_session(session)
    assert preamble.read_bytes() == derived_bytes, "derived bytes must survive"


def test_derived_preamble_fallback_override(tmp_path, monkeypatch) -> None:
    """D1 — the operator override forces the historical fallback."""
    from trellis.checker.isabelle_scaffold import (
        DERIVED_PREAMBLE_MARKER,
        PREAMBLE_ALLOW_FALLBACK_ENV,
        sync_session,
    )

    session = _derived_session(tmp_path, '"HOL-Probability.Probability"')
    (tmp_path / "Tablet" / "Preamble.thy").write_text("garbage", encoding="utf-8")
    monkeypatch.setenv(PREAMBLE_ALLOW_FALLBACK_ENV, "1")

    sync_session(session)
    body = (session / "Tablet_Preamble.thy").read_text(encoding="utf-8")
    assert DERIVED_PREAMBLE_MARKER not in body
    assert "Complex_Main" in body


def test_fresh_session_still_falls_back_without_a_worker_preamble(tmp_path) -> None:
    """D1 — stickiness must not break the fresh-repo path."""
    from trellis.checker.isabelle_scaffold import (
        DERIVED_PREAMBLE_MARKER,
        generate_preamble_thy,
        sync_session,
    )

    (tmp_path / "Tablet").mkdir(parents=True)
    session = tmp_path / "isabelle"
    session.mkdir()
    sync_session(session)  # no worker preamble at all
    body = (session / "Tablet_Preamble.thy").read_text(encoding="utf-8")
    assert DERIVED_PREAMBLE_MARKER not in body
    assert body == generate_preamble_thy(None)


def test_empty_import_list_renders_the_fallback(tmp_path) -> None:
    """D6 — an empty list must not render a malformed `imports \\nbegin`."""
    from trellis.checker.isabelle_scaffold import generate_preamble_thy

    assert generate_preamble_thy([]) == generate_preamble_thy(None)


def test_worker_seed_preamble_refresh_tracks_the_worker_preamble(tmp_path) -> None:
    """The worker-facing seed must not drift from the session's preamble.

    `<worker_repo>/isabelle/` is written once at setup; nothing refreshed it, so
    an edit to `Tablet/Preamble.thy` reached the checker's session dir but not
    the worker, which then compiled against a narrower import root than the gate
    used — the live system_feedback that surfaced this.
    """
    from trellis.checker.isabelle_scaffold import (
        DERIVED_PREAMBLE_MARKER,
        generate_preamble_thy,
        refresh_worker_seed_preamble,
    )

    (tmp_path / "Tablet").mkdir(parents=True)
    (tmp_path / "Tablet" / "Preamble.thy").write_text(
        'theory Tablet_Preamble\n  imports "HOL-Probability.Probability"\nbegin\n\nend\n',
        encoding="utf-8",
    )
    seed = tmp_path / "isabelle"
    seed.mkdir()
    stale = generate_preamble_thy(None)  # the setup-time constant
    (seed / "Tablet_Preamble.thy").write_text(stale, encoding="utf-8")
    (seed / "ROOT").write_text("session Tablet_Base in \"base\" = \"HOL-Probability\" +\n", encoding="utf-8")
    root_before = (seed / "ROOT").read_bytes()

    got = refresh_worker_seed_preamble(tmp_path)

    body = (seed / "Tablet_Preamble.thy").read_text(encoding="utf-8")
    assert got == ["HOL-Probability.Probability"]
    assert "HOL-Probability.Probability" in body
    assert DERIVED_PREAMBLE_MARKER in body
    # The seed's ROOT is node-less by design — the refresh must not touch it.
    assert (seed / "ROOT").read_bytes() == root_before
    # Idempotent.
    before = (seed / "Tablet_Preamble.thy").read_bytes()
    refresh_worker_seed_preamble(tmp_path)
    assert (seed / "Tablet_Preamble.thy").read_bytes() == before
