"""Goldens for the per-tablet Isabelle session SCAFFOLD generator (B2d).

Asserts the generated ``ROOT`` + ``Tablet_Preamble.thy`` byte-match a golden
for a 2-node fixture tablet, the session-qualified theory naming
(``Tablet_<Node>``, never a global name), the ROOT ``options`` block
(``quick_and_dirty = false``; NO ``proofs = 1``/``record_proofs``), the
sorted/deterministic theory list, the fail-closed stub for an absent node,
and the ``sync_session`` writer end-to-end (including that it derives the node
set from the present worker ``Tablet_<Node>.thy`` files and never rewrites a
worker body). Also exercises the ``isabelle_sync_session`` /
``isabelle_build_session`` server handlers (scaffold written under the
socket-derived repo; build is a no-op-success with no ROOT).
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Iterator

import pytest

from trellis.checker import isabelle_scaffold as scaffold
from trellis.checker.protocol import CheckerRequest
from trellis.checker.server import CheckerServer


# ============================ pure render goldens ============================

# The golden ROOT for a 2-node tablet {Alpha, Beta} (+ the always-present
# Tablet_Preamble base). Pinned byte-for-byte: the session-qualified names,
# the options block (quick_and_dirty=false, bounded threads/parallel_proofs/
# timeout, NO proofs=1), Preamble listed first, nodes sorted.
GOLDEN_ROOT_TWO_NODE = """\
(* Auto-generated by .trellis. Do not edit. *)
session Tablet = HOL +
  options [quick_and_dirty = false, threads = 2, parallel_proofs = 1, timeout = 1800]
  theories
    Tablet_Preamble
    Tablet_Alpha
    Tablet_Beta
"""

GOLDEN_PREAMBLE = """\
theory Tablet_Preamble
  imports Main
begin

end
"""


def test_golden_root_two_node() -> None:
    text = scaffold.generate_root(["Tablet_Alpha", "Tablet_Beta"])
    assert text == GOLDEN_ROOT_TWO_NODE


def test_golden_preamble() -> None:
    assert scaffold.generate_preamble_thy() == GOLDEN_PREAMBLE


def test_root_options_quick_and_dirty_false_and_no_proofs_option() -> None:
    """The soundness-relevant ROOT policy: quick_and_dirty=false (a stray
    sorry FAILS the build) and NO stale ``proofs``/``record_proofs`` option
    (invalid in 2025-2; oracle names record at level 0 regardless)."""
    text = scaffold.generate_root(["Tablet_Alpha"])
    assert "quick_and_dirty = false" in text
    # The stale option is a BARE ``proofs`` key; ``parallel_proofs`` is a
    # different, valid option, so match the bare key with a leading delimiter.
    assert "[proofs = " not in text and ", proofs = " not in text
    assert "record_proofs" not in text
    # The HOL parent + Tablet session name are fixed.
    assert "session Tablet = HOL +" in text


def test_node_theory_names_are_session_qualified() -> None:
    """Theory names are ``Tablet_<Node>`` (session-qualified), never a bare
    global name like ``Alpha`` (research 02 R5 — regular sessions must not
    claim global theory names)."""
    assert scaffold.node_theory_name("Alpha") == "Tablet_Alpha"
    render = scaffold.render_scaffold(["Alpha", "Beta"])
    assert list(render.node_theories) == ["Tablet_Alpha", "Tablet_Beta"]
    for theory in render.node_theories:
        assert theory.startswith("Tablet_")


def test_render_is_sorted_and_deterministic() -> None:
    """The node theory list is sorted (BTreeSet parity with the Lean umbrella)
    so the ROOT is byte-stable regardless of input order."""
    a = scaffold.render_scaffold(["Beta", "Alpha", "Gamma"])
    b = scaffold.render_scaffold(["Gamma", "Alpha", "Beta"])
    assert a.root_text == b.root_text
    assert list(a.node_theories) == ["Tablet_Alpha", "Tablet_Beta", "Tablet_Gamma"]


def test_preamble_pseudo_node_is_dropped_from_node_list() -> None:
    """A ``Preamble`` stem maps to the generated ``Tablet_Preamble`` base and
    is never emitted as a node theory (it is listed once, first, in ROOT)."""
    render = scaffold.render_scaffold(["Preamble", "Alpha"])
    assert list(render.node_theories) == ["Tablet_Alpha"]
    # Preamble appears exactly once in ROOT (the generated base line).
    assert render.root_text.count("Tablet_Preamble") == 1


def test_invalid_node_name_rejected() -> None:
    for bad in ["1bad", "has-dash", "has space", "", "a.b"]:
        with pytest.raises(ValueError):
            scaffold.render_scaffold([bad])


def test_absent_node_gets_fail_closed_stub_and_is_listed() -> None:
    """A registered node whose worker ``.thy`` is absent gets a fail-closed
    stub (an ``oops``'d ``False`` goal — the build FAILS, never silently
    drops the node) and is still listed in ROOT."""
    render = scaffold.render_scaffold(
        ["Alpha"], absent_node_stems=["Ghost"]
    )
    assert "Tablet_Ghost" in render.node_theories
    stub = render.node_stub_texts["Tablet_Ghost"]
    assert "theory Tablet_Ghost" in stub
    assert "imports Tablet_Preamble" in stub
    assert "lemma Ghost: False" in stub
    assert "oops" in stub
    # No ``sorry`` (which under quick_and_dirty=false would still fail, but the
    # intent is an unprovable, unfinished goal).
    assert "sorry" not in stub


# ============================ sync_session writer ============================


def test_sync_session_writes_root_and_preamble(tmp_path: Path) -> None:
    """End-to-end: two worker node theories present on disk ⇒ ROOT lists both
    (sorted) + Preamble, and the worker bodies are left UNTOUCHED."""
    session_dir = tmp_path / "isabelle"
    session_dir.mkdir()
    # Worker-authored complete node theories (the Tablet/<Node>.lean analogue).
    alpha_body = (
        "theory Tablet_Alpha\n  imports Tablet_Preamble\nbegin\n\n"
        'lemma Alpha: "(1::nat)+1=2" by simp\n\nend\n'
    )
    beta_body = (
        "theory Tablet_Beta\n  imports Tablet_Preamble Tablet_Alpha\nbegin\n\n"
        'lemma Beta: "(2::nat)+0=2" by simp\n\nend\n'
    )
    (session_dir / "Tablet_Alpha.thy").write_text(alpha_body, encoding="utf-8")
    (session_dir / "Tablet_Beta.thy").write_text(beta_body, encoding="utf-8")

    summary = scaffold.sync_session(session_dir)

    assert (session_dir / "ROOT").read_text(encoding="utf-8") == GOLDEN_ROOT_TWO_NODE
    assert (session_dir / "Tablet_Preamble.thy").read_text(
        encoding="utf-8"
    ) == GOLDEN_PREAMBLE
    # Worker bodies are NOT rewritten by the generator.
    assert (session_dir / "Tablet_Alpha.thy").read_text(encoding="utf-8") == alpha_body
    assert (session_dir / "Tablet_Beta.thy").read_text(encoding="utf-8") == beta_body
    assert summary["node_theories"] == ["Tablet_Alpha", "Tablet_Beta"]


def test_sync_session_empty_dir_writes_preamble_only_root(tmp_path: Path) -> None:
    session_dir = tmp_path / "isabelle"
    summary = scaffold.sync_session(session_dir)
    root = (session_dir / "ROOT").read_text(encoding="utf-8")
    assert "Tablet_Preamble" in root
    # No node theories listed beyond the Preamble base.
    assert summary["node_theories"] == []
    assert (session_dir / "Tablet_Preamble.thy").is_file()


def test_sync_session_absent_expected_node_writes_stub(tmp_path: Path) -> None:
    """When the caller registers an expected node set, an expected node with no
    worker ``.thy`` on disk gets a fail-closed stub file written."""
    session_dir = tmp_path / "isabelle"
    session_dir.mkdir()
    (session_dir / "Tablet_Alpha.thy").write_text(
        "theory Tablet_Alpha\n  imports Tablet_Preamble\nbegin\nend\n",
        encoding="utf-8",
    )
    summary = scaffold.sync_session(session_dir, node_stems=["Alpha", "Ghost"])
    assert (session_dir / "Tablet_Ghost.thy").is_file()
    stub = (session_dir / "Tablet_Ghost.thy").read_text(encoding="utf-8")
    assert "oops" in stub
    assert "Tablet_Ghost" in summary["node_theories"]
    assert "Tablet_Alpha" in summary["node_theories"]


def test_sync_session_ignores_stray_non_node_thy(tmp_path: Path) -> None:
    """A stray ``.thy`` that is not a ``Tablet_<Node>`` file is ignored, not
    fatal (robust to a dirty session dir)."""
    session_dir = tmp_path / "isabelle"
    session_dir.mkdir()
    (session_dir / "Tablet_Alpha.thy").write_text(
        "theory Tablet_Alpha\n  imports Tablet_Preamble\nbegin\nend\n",
        encoding="utf-8",
    )
    # A loose, non-conforming theory file.
    (session_dir / "Scratch.thy").write_text("theory Scratch begin end\n", encoding="utf-8")
    summary = scaffold.sync_session(session_dir)
    assert summary["node_theories"] == ["Tablet_Alpha"]


# ============================ server handler wiring ============================


@pytest.fixture
def runtime_root() -> Iterator[Path]:
    base = Path(tempfile.mkdtemp(prefix="isa-scaffold-", dir="/tmp"))
    repo = base / "r"
    runtime = repo / ".trellis" / "runtime" / "rt"
    runtime.mkdir(parents=True)
    (repo / "Tablet").mkdir(parents=True)
    yield runtime
    import shutil

    shutil.rmtree(base, ignore_errors=True)


def test_handler_sync_session_writes_scaffold_under_socket_repo(
    runtime_root: Path,
) -> None:
    """``isabelle_sync_session`` writes the scaffold into the socket-derived
    ``<supervisor_repo>/isabelle/`` dir — never a request-supplied path."""
    server = CheckerServer(runtime_root, parallelism=1, socket_group_gid=None)
    server.set_expected_peer_uid(os.geteuid())
    session_dir = server.supervisor_repo / "isabelle"
    session_dir.mkdir(parents=True, exist_ok=True)
    (session_dir / "Tablet_Alpha.thy").write_text(
        "theory Tablet_Alpha\n  imports Tablet_Preamble\nbegin\nend\n",
        encoding="utf-8",
    )

    req = CheckerRequest(op="isabelle_sync_session", request_id=1, timeout_secs=60.0)
    response, rc, log_extra = server._handle_isabelle_workspace_op(req)

    assert rc == 0
    assert response["returncode"] == 0
    summary = json.loads(response["stdout"])
    assert summary["node_theories"] == ["Tablet_Alpha"]
    assert (session_dir / "ROOT").is_file()
    assert (session_dir / "Tablet_Preamble.thy").is_file()
    # The path the handler used is under the socket-derived supervisor repo.
    assert str(server.supervisor_repo) in log_extra["isabelle_session_dir"]


def test_handler_build_session_noop_success_without_root(
    runtime_root: Path,
) -> None:
    """``isabelle_build_session`` is a no-op-success when no scaffold ROOT
    exists (the production state — no IsabelleHol tablet live), so the
    kernel's precondition path is satisfied without spawning ``isabelle``."""
    server = CheckerServer(runtime_root, parallelism=1, socket_group_gid=None)
    server.set_expected_peer_uid(os.geteuid())

    req = CheckerRequest(op="isabelle_build_session", request_id=2, timeout_secs=60.0)
    response, rc, _ = server._handle_isabelle_workspace_op(req)
    assert rc == 0
    assert response["returncode"] == 0
