//! Emit the set of prompt fragments that have an `_isabelle` sibling.
//!
//! Backend variants used to be selected by a hand-written conditional at each
//! call site, so adding a variant and forgetting the conditional silently sent
//! Lean text to an Isabelle run. Scanning at build time makes the variant FILE
//! the only thing anyone has to add: the routing table is regenerated from disk
//! on every build, and `kernel/tests/isabelle_prompt_decontamination.rs` fails
//! if a Lean variant is ever emitted while its sibling exists.
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn walk(dir: &Path, root: &Path, out: &mut BTreeMap<String, String>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(&path, root, out);
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else { continue };
        let Some(stem) = name.strip_suffix("_isabelle.md") else { continue };
        let lean = path.with_file_name(format!("{stem}.md"));
        if !lean.is_file() {
            continue;
        }
        let rel = |p: &Path| {
            p.strip_prefix(root)
                .ok()
                .and_then(|r| r.to_str())
                .map(|s| s.replace('\\', "/"))
        };
        if let (Some(k), Some(v)) = (rel(&lean), rel(&path)) {
            out.insert(k, v);
        }
    }
}

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("trellis")
        .join("prompt_fragments");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut twins = BTreeMap::new();
    walk(&root, &root, &mut twins);

    let mut src = String::from(
        "// @generated by build.rs — Lean fragment id -> its `_isabelle` sibling.\n\
         pub const ISABELLE_FRAGMENT_TWINS: &[(&str, &str)] = &[\n",
    );
    for (lean, isa) in &twins {
        src.push_str(&format!("    ({lean:?}, {isa:?}),\n"));
    }
    src.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("isabelle_fragment_twins.rs");
    std::fs::write(&out, src).expect("write isabelle_fragment_twins.rs");
}
