use crate::model::{ApprovedTargetSnapshot, NodeId};
use crate::worker_normalization::present_nodes_from_repo;
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TabletRootSyncOutput {
    pub node_names: BTreeSet<NodeId>,
    pub tablet_root_path: String,
}

pub fn generate_tablet_root_lean(node_names: &BTreeSet<NodeId>) -> String {
    let mut lines = vec!["-- Auto-generated by .trellis. Do not edit.".to_string()];
    for name in node_names {
        lines.push(format!("import Tablet.{name}"));
    }
    lines.push(String::new());
    lines.join("\n")
}

fn write_text(path: &Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("failed to create {}: {err}", parent.display()))?;
    }
    fs::write(path, content).map_err(|err| format!("failed to write {}: {err}", path.display()))
}

pub fn sync_tablet_root(
    repo_path: &Path,
    node_names: &BTreeSet<NodeId>,
) -> Result<TabletRootSyncOutput, String> {
    let root_path = repo_path.join("Tablet.lean");
    write_text(&root_path, &generate_tablet_root_lean(node_names))?;
    Ok(TabletRootSyncOutput {
        node_names: node_names.clone(),
        tablet_root_path: root_path.display().to_string(),
    })
}

pub fn sync_tablet_root_from_repo(repo_path: &Path) -> Result<TabletRootSyncOutput, String> {
    let node_names = present_nodes_from_repo(repo_path)?;
    sync_tablet_root(repo_path, &node_names)
}

/// Resolve the umbrella node set for the paper-target `Tablet.lean`
/// emitted at the `Phase::ProofFormalization → Phase::Cleanup`
/// transition. Iterates `approved.configured_targets`, gathers the
/// covering `NodeId`s from `approved.coverage`, and unconditionally
/// inserts `NodeId::from("Preamble")` so a downstream `import Tablet`
/// retains the mathlib import root even on degenerate `coverage`.
///
/// `approved.protected_closure_nodes` is intentionally NOT included:
/// those nodes are reached transitively via the covering nodes' Lean
/// imports, and broadening the umbrella to the full protection
/// surface reintroduces the elaboration-time bloat we're avoiding.
///
/// Pure function — easy to unit-test against synthetic
/// `ApprovedTargetSnapshot` fixtures and used by the runtime CLI
/// dispatcher for `ProtocolCommand::SyncTabletRootForPaperTargets`.
pub fn paper_target_umbrella_nodes(approved: &ApprovedTargetSnapshot) -> BTreeSet<NodeId> {
    let mut nodes: BTreeSet<NodeId> = BTreeSet::new();
    for target in &approved.configured_targets {
        if let Some(covering) = approved.coverage.get(target) {
            for node in covering {
                nodes.insert(node.clone());
            }
        }
    }
    nodes.insert(NodeId::from("Preamble"));
    nodes
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::TargetId;
    use std::collections::BTreeMap;
    use tempfile::tempdir;

    fn nodes_from(items: &[&str]) -> BTreeSet<NodeId> {
        items.iter().map(|s| NodeId::from(*s)).collect()
    }

    #[test]
    fn paper_target_umbrella_nodes_extracts_coverage_union() {
        // Three targets with overlapping coverage; the union of values
        // ∪ {Preamble} is the umbrella set.
        let mut coverage: BTreeMap<TargetId, BTreeSet<NodeId>> = BTreeMap::new();
        coverage.insert(TargetId::from("t1"), nodes_from(&["A", "B"]));
        coverage.insert(TargetId::from("t2"), nodes_from(&["B", "C"]));
        coverage.insert(TargetId::from("t3"), nodes_from(&["D"]));
        let approved = ApprovedTargetSnapshot {
            configured_targets: [
                TargetId::from("t1"),
                TargetId::from("t2"),
                TargetId::from("t3"),
            ]
            .into_iter()
            .collect(),
            coverage,
            protected_closure_nodes: BTreeSet::new(),
        };
        let umbrella = paper_target_umbrella_nodes(&approved);
        assert_eq!(umbrella, nodes_from(&["A", "B", "C", "D", "Preamble"]));
    }

    #[test]
    fn paper_target_umbrella_nodes_skips_protected_closure_nodes() {
        // Documents the "covering only, not protection surface" design
        // decision: protected_closure_nodes are reached transitively
        // via covering nodes' Lean imports and would re-introduce
        // bloat at the umbrella level.
        let mut coverage: BTreeMap<TargetId, BTreeSet<NodeId>> = BTreeMap::new();
        coverage.insert(TargetId::from("t1"), nodes_from(&["A"]));
        let approved = ApprovedTargetSnapshot {
            configured_targets: [TargetId::from("t1")].into_iter().collect(),
            coverage,
            protected_closure_nodes: nodes_from(&["X", "Y"]),
        };
        let umbrella = paper_target_umbrella_nodes(&approved);
        assert_eq!(umbrella, nodes_from(&["A", "Preamble"]));
        assert!(!umbrella.contains(&NodeId::from("X")));
        assert!(!umbrella.contains(&NodeId::from("Y")));
    }

    #[test]
    fn paper_target_umbrella_nodes_handles_empty_coverage() {
        // Defensive baseline — shouldn't happen post-TheoremStating,
        // but degrades to the {Preamble}-only file rather than an
        // error so a downstream `import Tablet` build still parses.
        let approved = ApprovedTargetSnapshot::default();
        let umbrella = paper_target_umbrella_nodes(&approved);
        assert_eq!(umbrella, nodes_from(&["Preamble"]));
        assert_eq!(
            generate_tablet_root_lean(&umbrella),
            "-- Auto-generated by .trellis. Do not edit.\nimport Tablet.Preamble\n"
        );
    }

    #[test]
    fn paper_target_umbrella_nodes_matches_live_multi_target_shape() {
        // Exercises a realistic multi-target `approved_targets` snapshot
        // and verifies the umbrella set matches the five paper-target
        // covering nodes ∪ {Preamble}.
        let mut coverage: BTreeMap<TargetId, BTreeSet<NodeId>> = BTreeMap::new();
        coverage.insert(
            TargetId::from("thm:close"),
            nodes_from(&["CloseToDiagonalTheorem"]),
        );
        coverage.insert(
            TargetId::from("thm:k-Ck"),
            nodes_from(&["LinearOffDiagonalTheorem"]),
        );
        coverage.insert(TargetId::from("thm:main"), nodes_from(&["MainTheorem"]));
        coverage.insert(
            TargetId::from("thm:multicolor"),
            nodes_from(&["MulticolorTheorem"]),
        );
        coverage.insert(
            TargetId::from("thm:off-diagonal-general"),
            nodes_from(&["OffDiagonalGeneralTheorem"]),
        );
        let approved = ApprovedTargetSnapshot {
            configured_targets: [
                TargetId::from("thm:close"),
                TargetId::from("thm:k-Ck"),
                TargetId::from("thm:main"),
                TargetId::from("thm:multicolor"),
                TargetId::from("thm:off-diagonal-general"),
            ]
            .into_iter()
            .collect(),
            coverage,
            protected_closure_nodes: nodes_from(&[
                "MulticolorRamseyNumber",
                "MulticolorRamseyProperty",
                "RamseyNumber",
                "RamseyProperty",
            ]),
        };
        let umbrella = paper_target_umbrella_nodes(&approved);
        assert_eq!(
            umbrella,
            nodes_from(&[
                "CloseToDiagonalTheorem",
                "LinearOffDiagonalTheorem",
                "MainTheorem",
                "MulticolorTheorem",
                "OffDiagonalGeneralTheorem",
                "Preamble",
            ])
        );
    }

    #[test]
    fn sync_tablet_root_writes_paper_target_umbrella_to_tempdir() {
        // Integration-style: dispatch the resolved umbrella through
        // the existing `sync_tablet_root` primitive into a tempdir
        // and inspect the byte-for-byte file content.
        let tmp = tempdir().expect("tempdir");
        let repo = tmp.path().join("repo");
        std::fs::create_dir_all(&repo).expect("repo dir");
        let mut coverage: BTreeMap<TargetId, BTreeSet<NodeId>> = BTreeMap::new();
        coverage.insert(TargetId::from("t1"), nodes_from(&["Foo"]));
        coverage.insert(TargetId::from("t2"), nodes_from(&["Bar"]));
        let approved = ApprovedTargetSnapshot {
            configured_targets: [TargetId::from("t1"), TargetId::from("t2")]
                .into_iter()
                .collect(),
            coverage,
            protected_closure_nodes: BTreeSet::new(),
        };
        let umbrella = paper_target_umbrella_nodes(&approved);
        sync_tablet_root(&repo, &umbrella).expect("sync");
        let written = std::fs::read_to_string(repo.join("Tablet.lean")).expect("read root");
        assert_eq!(
            written,
            "-- Auto-generated by .trellis. Do not edit.\nimport Tablet.Bar\nimport Tablet.Foo\nimport Tablet.Preamble\n"
        );
    }

    #[test]
    fn generate_tablet_root_is_sorted() {
        let nodes = BTreeSet::from([
            NodeId::from("b"),
            NodeId::from("Preamble"),
            NodeId::from("a"),
        ]);
        let text = generate_tablet_root_lean(&nodes);
        assert_eq!(
            text,
            "-- Auto-generated by .trellis. Do not edit.\nimport Tablet.Preamble\nimport Tablet.a\nimport Tablet.b\n"
        );
    }

    #[test]
    fn sync_tablet_root_from_repo_writes_root_module() {
        let tmp = tempdir().expect("tempdir");
        let repo = tmp.path().join("repo");
        fs::create_dir_all(repo.join("Tablet")).expect("tablet dir");
        fs::write(repo.join("Tablet/Preamble.lean"), "import Mathlib\n")
            .expect("write preamble lean");
        fs::write(repo.join("Tablet/Preamble.tex"), "").expect("write preamble tex");
        fs::write(repo.join("Tablet/A.lean"), "import Tablet.Preamble\n").expect("write A lean");
        fs::write(
            repo.join("Tablet/A.tex"),
            "\\begin{definition}A\\end{definition}\n",
        )
        .expect("write A tex");

        let output = sync_tablet_root_from_repo(&repo).expect("sync tablet root");

        assert_eq!(
            output.node_names,
            BTreeSet::from([NodeId::from("A"), NodeId::from("Preamble")])
        );
        assert_eq!(
            fs::read_to_string(repo.join("Tablet.lean")).expect("read root"),
            "-- Auto-generated by .trellis. Do not edit.\nimport Tablet.A\nimport Tablet.Preamble\n"
        );
    }
}
