"""Supervisor-owned authoritative workspace helpers."""

from __future__ import annotations

import errno
import json
import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict

from trellis.project_paths import (
    project_state_dir_for_repo,
    supervisor_root_dir,
    supervisor_workspace_cache_path,
    supervisor_workspace_home_path,
    supervisor_workspace_marker_path,
    supervisor_workspace_repo_path,
)


_EXCLUDED_NAMES = {
    ".git",
    ".lake",
    ".trellis",
    ".trellis-history",
    ".pytest_cache",
    ".viewer",
    "__pycache__",
    "node_modules",
    "target",
}


# Lake packages whose oleans are legitimately absent and can never be needed.
#
# `lake exe cache get` fetches Mathlib's olean cache: Mathlib plus every
# package Mathlib's *library* imports. `Cli` is not one of them. It enters the
# manifest only because `importGraph` requires it, and inside `importGraph`
# only the two EXECUTABLE roots reach it (`MainGraph.lean` and
# `MainUnusedTransitiveImports.lean`, via `import Cli.Basic`); the
# `ImportGraph` lean_lib imports nothing from `Cli`. The one other importer in
# the whole tree is `MathlibTest/import_all.lean`, which is not in any target
# the run builds. No module reachable from `Tablet` or from `import Mathlib`
# reaches `Cli`, so its oleans are never demanded and their absence cannot
# fail a build.
#
# `setup_ops.run_setup_prewarm` builds `Cli` at setup time so newly prewarmed
# repos have no gap; repos prewarmed before that landed keep the gap forever
# and have no repair path, which is why this list exists rather than a
# stronger assertion.
_OLEAN_OPTIONAL_PACKAGES = frozenset({"Cli"})


@dataclass(frozen=True)
class SupervisorWorkspacePaths:
    root: Path
    repo: Path
    home: Path
    cache: Path
    marker: Path


def _paths(worker_repo: Path) -> SupervisorWorkspacePaths:
    worker_repo = worker_repo.resolve()
    repo = supervisor_workspace_repo_path(worker_repo).resolve()
    return SupervisorWorkspacePaths(
        root=supervisor_root_dir(worker_repo).resolve(),
        repo=repo,
        home=supervisor_workspace_home_path(worker_repo).resolve(),
        cache=supervisor_workspace_cache_path(worker_repo).resolve(),
        marker=supervisor_workspace_marker_path(repo).resolve(),
    )


def authoritative_repo_path(worker_repo: Path) -> Path:
    return _paths(worker_repo.resolve()).repo


def _skip_name(name: str) -> bool:
    return name in _EXCLUDED_NAMES or name.startswith(".tmp")


def _copy_file_if_needed(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    try:
        src_stat = src.stat()
    except OSError:
        return
    if dst.exists():
        try:
            dst_stat = dst.stat()
            if (
                dst_stat.st_size == src_stat.st_size
                and dst_stat.st_mtime_ns == src_stat.st_mtime_ns
            ):
                return
        except OSError:
            pass
    # `shutil.copy2` writes the content via group-writable access (works for
    # supervisor → burst-user:supervisor-group files), then `copystat` calls
    # `os.chmod` which requires *owning* the dest. Worker-burst-created
    # tablet files (INDEX.md, README.md regenerated by `sync-tablet-support`
    # inside the bwrap sandbox) are owned by the burst user; chmod from the
    # supervisor user raises EPERM. The content copy already succeeded
    # by that point — we only lose mtime preservation, which is a perf hint
    # for the size+mtime skip-fast-path above (next call will re-copy
    # unnecessarily but correctness is unaffected). Treat EPERM as success.
    try:
        shutil.copy2(src, dst)
        # Normalise group-read perms after copy. The verifier lane runs as
        # the burst user (member of the supervisor's group) and must be
        # able to read every Tablet file; some agent backends produce files
        # with mode 0o600 (e.g. mktemp+rename patterns that bypass umask),
        # and `shutil.copy2` preserves the source mode while assigning the
        # supervisor's uid to the dst. Without this chmod, a
        # mode-600 supervisor-owned file is owner-only, denying the
        # verifier read access. Mode 0o664 mirrors the rest of the tablet
        # — owner+group rw, world r — and lets both worker writes (via the
        # shared supervisor group) and verifier reads succeed.
        try:
            os.chmod(dst, 0o664)
        except OSError as chmod_exc:
            # When dst is owned by the burst user (auto-managed
            # INDEX.md/README.md case), supervisor lacks chmod rights.
            # The file already has whatever perms the worker wrote, which
            # is fine — same EPERM-tolerance as copystat above.
            if chmod_exc.errno != errno.EPERM:
                raise
    except OSError as exc:
        if exc.errno != errno.EPERM:
            raise


def _copy_artifact_atomic_if_needed(src: Path, dst: Path) -> bool:
    """Atomically mirror a build artifact (olean/ilean/trace/hash) src → dst.

    Returns ``True`` if a copy occurred, ``False`` if skipped as already-current.

    Idempotent: skips when dst already matches src by size + mtime (the same
    fast-path ``_copy_file_if_needed`` uses). When a copy is needed, writes to a
    sibling temp file and ``os.replace``s it into place so a concurrent reader
    (e.g. an in-flight ``lake env lean``) never observes a half-written binary
    olean. ``shutil.copy2`` preserves mtime on the temp, and ``os.replace``
    preserves it through the rename, so the size+mtime skip holds on re-runs.
    Best-effort: any OSError is swallowed (mirrors the EPERM-tolerance of
    ``_copy_file_if_needed`` — a failed mirror just leaves the prior artifact).
    """
    try:
        src_stat = src.stat()
    except OSError:
        return False
    if dst.exists():
        try:
            dst_stat = dst.stat()
            if (
                dst_stat.st_size == src_stat.st_size
                and dst_stat.st_mtime_ns == src_stat.st_mtime_ns
            ):
                return False
        except OSError:
            pass
    tmp = dst.with_name(f"{dst.name}.tmp.{os.getpid()}")
    try:
        shutil.copy2(src, tmp)
        try:
            os.chmod(tmp, 0o664)
        except OSError as chmod_exc:
            if chmod_exc.errno != errno.EPERM:
                raise
        os.replace(tmp, dst)
        return True
    except OSError:
        try:
            tmp.unlink(missing_ok=True)
        except OSError:
            pass
        return False


def propagate_tablet_back_to_worker(
    supervisor_repo: Path, worker_repo: Path
) -> Dict[str, int]:
    """Copy kernel-mutated `Tablet/` files from supervisor → worker.

    Two kernel-side processes write to the supervisor's `Tablet/` directory
    during a worker request lifecycle:
      1. `sync_tablet_support` (`atomic_actions/tablet_support.py`) regenerates
         `Tablet/INDEX.md`, `Tablet/README.md`, `Tablet/header.tex` from the
         current kernel state.
      2. `ensure_preamble_import_for_orphan` (`kernel/src/filespec.rs:232`,
         invoked from `validate_worker_result`) injects `import Tablet.Preamble`
         into orphan node `.lean` files.
    Both modify the supervisor repo (the authoritative_repo the kernel sees).
    Without this back-propagation, the worker repo (which
    `git_checkpoint_hook.py` actually commits) silently diverges from the
    kernel's view, with two destructive consequences:

      a. git HEAD ends up missing the kernel's mutations → after a checkpoint
         the kernel-blessed state is lost from history.
      b. The validator's `before_snapshot` (captured from supervisor) doesn't
         match what's on the worker repo's disk for these auto-managed files,
         so the validator reports phantom modifications — the worker is
         rejected for changes it never made and cannot revert from inside its
         Easy-mode scope. Loop is unrecoverable.

    Copies all `Tablet/*.lean`, `Tablet/*.tex`, and the three auto-managed
    docs (`INDEX.md`, `README.md`, `header.tex`) from supervisor → worker.
    Idempotent (size/mtime check) and safe to call after every Valid/Invalid
    worker normalization.
    """
    src_tablet = (supervisor_repo / "Tablet").resolve()
    dst_tablet = (worker_repo / "Tablet").resolve()
    copied = 0
    if not src_tablet.is_dir() or not dst_tablet.is_dir():
        return {"copied_files": 0}
    for src in src_tablet.iterdir():
        if not src.is_file():
            continue
        # Auto-managed by sync_tablet_support: regenerated each prep.
        is_managed_doc = src.name in {"INDEX.md", "README.md", "header.tex"}
        # Tablet node content: subject to ensure_preamble_import_for_orphan.
        is_node_file = src.suffix in {".lean", ".tex"}
        if not (is_managed_doc or is_node_file):
            continue
        dst = dst_tablet / src.name
        before_exists = dst.exists()
        before_mtime = dst.stat().st_mtime_ns if before_exists else None
        _copy_file_if_needed(src, dst)
        if not before_exists or (
            dst.exists() and dst.stat().st_mtime_ns != before_mtime
        ):
            copied += 1

    # Mirror the kernel-current compiled interface (oleans) supervisor → worker.
    #
    # The source copy above keeps the worker's `Tablet/*.lean` in lockstep with
    # the kernel's authoritative view, but the matching `.lake/build` artifacts
    # are NOT covered by `_sync_repo_tree` (which excludes `.lake/` so each role
    # keeps its own build outputs). The supervisor repo's oleans are rebuilt
    # current during acceptance; the worker repo's are only lazily (re)built
    # when an agent burst happens to recompile a node. Result: after a node's
    # source is back-propagated, the worker repo can carry source NEWER than its
    # olean. A reviewer's `lake env lean <scratch.lean>` probe runs bare `lean`
    # (no freshness check, no rebuild — it just resolves imports off
    # `LEAN_PATH`), so it reads whatever olean is on disk: an out-of-date
    # compiled interface (e.g. a structure field present in source but missing
    # from the olean), which makes the reviewer emit a spurious `system_feedback`
    # that halts the supervisor. Mirroring the supervisor's current per-node
    # complete `.olean` bundle (plus `.ilean`/`.trace` and hash companions) keeps the
    # worker's compiled interface in step with the source it just received.
    # Oleans are relocatable across the two repos (identical toolchain +
    # hardlinked package layout — verified byte-identical for unchanged nodes).
    # The load-bearing artifact is the ordered exported/server/private `.olean`
    # bundle; the `.ilean`/`.trace`/`.hash` companions are mirrored so any
    # subsequent `lake build` against the worker tree sees a coherent, current
    # artifact set rather than a torn one.
    #
    # Copies are atomic (temp + os.replace) to avoid a concurrent reader seeing a
    # half-written binary olean, and idempotent (size+mtime skip). Orphan
    # artifacts — build outputs for nodes no longer in the authoritative Tablet —
    # are purged, mirroring the kernel's own `purge_stale_tablet_build_artifacts`
    # so the worker's import resolver never trips over a dangling olean.
    oleans_mirrored = 0
    oleans_purged = 0
    # Suffixes consulted/loaded by the reviewer probe + any later `lake build`.
    mirror_suffixes = (
        ".olean",
        ".olean.server",
        ".olean.private",
        ".olean.hash",
        ".olean.server.hash",
        ".olean.private.hash",
        ".ilean",
        ".ilean.hash",
        ".trace",
    )
    # Full per-node artifact set the kernel recognises (for orphan purge).
    all_artifact_suffixes = (
        ".olean",
        ".olean.server",
        ".olean.private",
        ".olean.hash",
        ".olean.server.hash",
        ".olean.private.hash",
        ".ilean",
        ".ilean.hash",
        ".c",
        ".c.hash",
        ".ll",
        ".trace",
    )
    src_build = (supervisor_repo / ".lake" / "build" / "lib" / "lean" / "Tablet").resolve()
    dst_build = (worker_repo / ".lake" / "build" / "lib" / "lean" / "Tablet").resolve()
    present_stems = {p.stem for p in src_tablet.glob("*.lean")}
    if src_build.is_dir() and present_stems:
        dst_build.mkdir(parents=True, exist_ok=True)
        for stem in present_stems:
            for suffix in mirror_suffixes:
                art_src = src_build / f"{stem}{suffix}"
                if not art_src.is_file():
                    continue
                art_dst = dst_build / f"{stem}{suffix}"
                if _copy_artifact_atomic_if_needed(art_src, art_dst):
                    oleans_mirrored += 1
        # Purge worker build artifacts whose node source no longer exists in the
        # authoritative Tablet. Guarded by `present_stems` being non-empty above
        # so a transient/empty supervisor Tablet never wipes the worker tree.
        if dst_build.is_dir():
            for art in dst_build.iterdir():
                if not art.is_file():
                    continue
                stem = None
                for suffix in sorted(all_artifact_suffixes, key=len, reverse=True):
                    if art.name.endswith(suffix):
                        stem = art.name[: -len(suffix)]
                        break
                if stem and stem not in present_stems:
                    try:
                        art.unlink()
                        oleans_purged += 1
                    except OSError:
                        pass

    return {
        "copied_files": copied,
        "oleans_mirrored": oleans_mirrored,
        "oleans_purged": oleans_purged,
    }


def invalidate_content_stale_supervisor_build_artifacts(
    supervisor_repo: Path,
) -> int:
    """Remove Tablet build artifacts whose content provenance is stale.

    The supervisor source sync deliberately preserves ``.lake``.  A rewind can
    therefore copy checkpoint sources over that workspace while leaving oleans
    from the abandoned line.  Bare Lean imports do not perform Lake's source
    freshness check, so retaining even one stale artifact can make a semantic
    observation read pre-rewind bytes.

    Staleness is decided per node by the ``.olean.srcclosure`` provenance
    sidecar (``observations.olean_is_content_current``): a node's artifact set
    is removed exactly when the sidecar's source-closure content hash
    disagrees with the current sources (or provenance cannot be established —
    the sidecar mechanism's fail-closed direction, matching every other
    consumer of these sidecars). Source mtimes are never consulted: a sync
    restamps essentially every Tablet source mtime, so any mtime cutoff
    degenerates to "newer than every artifact" and sweeps the whole tree.

    Best-effort and fail-open at the sweep level: any unexpected error leaves
    the remaining artifacts in place and never propagates to the caller (this
    runs on the acceptance path).
    """

    removed = 0
    try:
        # Imported at call time: ``observations`` imports this module at
        # module level (``authoritative_env_for_repo``), so a top-level
        # reverse import would be a cycle.
        from trellis.atomic_actions.observations import olean_is_content_current

        build_dir = supervisor_repo / ".lake" / "build" / "lib" / "lean" / "Tablet"
        if not build_dir.is_dir():
            return 0
        artifacts_by_stem: Dict[str, list[Path]] = {}
        for artifact in build_dir.iterdir():
            try:
                if artifact.is_file():
                    stem = artifact.name.split(".", 1)[0]
                    artifacts_by_stem.setdefault(stem, []).append(artifact)
            except OSError:
                continue
        for stem, artifacts in sorted(artifacts_by_stem.items()):
            try:
                if olean_is_content_current(supervisor_repo, stem):
                    continue
                for artifact in artifacts:
                    try:
                        artifact.unlink()
                        removed += 1
                    except OSError:
                        pass
            except Exception:
                # Skip this node (leave its artifacts alone) and keep
                # sweeping the rest.
                continue
    except Exception:
        return removed
    return removed


def _sync_repo_tree(worker_repo: Path, supervisor_repo: Path) -> Dict[str, int]:
    desired_files: set[Path] = set()
    desired_dirs: set[Path] = {Path(".")}
    copied_files = 0
    tablet_sources_refreshed = False

    for current, dirnames, filenames in os.walk(worker_repo):
        current_path = Path(current)
        rel_dir = current_path.relative_to(worker_repo)
        # The top-level `isabelle/` subtree is checker-owned: the checker's
        # `isabelle_scaffold.sync_session` is its only writer. Copying the
        # worker's setup-time seed here would revert the checker's current
        # ROOT/Tablet_Preamble.thy to the stale seed.
        dirnames[:] = [
            name
            for name in dirnames
            if not _skip_name(name)
            and not (rel_dir == Path(".") and name == "isabelle")
        ]
        desired_dirs.add(rel_dir)
        target_dir = supervisor_repo / rel_dir if rel_dir != Path(".") else supervisor_repo
        target_dir.mkdir(parents=True, exist_ok=True)
        for name in filenames:
            if _skip_name(name):
                continue
            rel_path = rel_dir / name if rel_dir != Path(".") else Path(name)
            desired_files.add(rel_path)
            src = worker_repo / rel_path
            dst = supervisor_repo / rel_path
            before = dst.exists()
            needs_copy = True
            try:
                src_stat = src.stat()
                if before:
                    dst_stat = dst.stat()
                    needs_copy = not (
                        dst_stat.st_size == src_stat.st_size
                        and dst_stat.st_mtime_ns == src_stat.st_mtime_ns
                    )
                if (
                    needs_copy
                    and rel_path.parent == Path("Tablet")
                    and rel_path.suffix == ".lean"
                ):
                    tablet_sources_refreshed = True
            except OSError:
                pass
            _copy_file_if_needed(src, dst)
            if not before or dst.exists():
                copied_files += 1

    preserved_roots = {Path(".lake"), Path(".trellis"), Path(".trellis-supervisor.json")}
    for current, dirnames, filenames in os.walk(supervisor_repo, topdown=False):
        current_path = Path(current)
        rel_dir = current_path.relative_to(supervisor_repo)
        if rel_dir == Path("."):
            continue
        # `isabelle/` (whole subtree) is checker-owned: its projections and
        # in-flight scratch never exist in the worker repo, so deleting
        # not-in-worker files here would destroy them mid-probe.
        if (
            rel_dir in preserved_roots
            or rel_dir.parts[0] == "isabelle"
            or any(part in {".lake", ".trellis"} for part in rel_dir.parts)
        ):
            continue
        for name in filenames:
            rel_path = rel_dir / name
            if rel_path in desired_files:
                continue
            (supervisor_repo / rel_path).unlink(missing_ok=True)
        for name in dirnames:
            rel_path = rel_dir / name
            if rel_path in desired_dirs:
                continue
            full = supervisor_repo / rel_path
            if rel_path in preserved_roots or name in {".lake", ".trellis"}:
                continue
            shutil.rmtree(full, ignore_errors=True)
        if rel_dir not in desired_dirs:
            shutil.rmtree(current_path, ignore_errors=True)

    stale_build_artifacts_removed = 0
    if tablet_sources_refreshed:
        stale_build_artifacts_removed = (
            invalidate_content_stale_supervisor_build_artifacts(supervisor_repo)
        )

    return {
        "copied_files": copied_files,
        "tracked_files": len(desired_files),
        "tracked_dirs": len(desired_dirs),
        "stale_build_artifacts_removed": stale_build_artifacts_removed,
    }


def _write_marker(worker_repo: Path, paths: SupervisorWorkspacePaths) -> Dict[str, Any]:
    payload = {
        "worker_repo_path": str(worker_repo.resolve()),
        "supervisor_repo_path": str(paths.repo),
        "supervisor_home": str(paths.home),
        "supervisor_cache": str(paths.cache),
    }
    paths.marker.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return payload


def _ensure_supervisor_lake_packages(
    worker_repo: Path, supervisor_repo: Path
) -> Dict[str, int]:
    """One-time hardlink of ``<worker>/.lake/packages`` → ``<supervisor>/.lake/packages``.

    Worker-side packages are populated by ``setup_repo.sh``'s burst-user
    prewarm path (``lake exe cache get`` runs as the burst user outside
    the lake_compiler bwrap). The supervisor workspace's ``_sync_repo_tree``
    excludes ``.lake/`` entirely so each role keeps its own build outputs,
    but that means the supervisor repo has NO package source on first sync.

    With ``--with-checker-rpc`` mode, lake invocations route through the
    ``lake_compiler`` bwrap, whose writable allowlist excludes
    ``.lake/packages/`` by design (PERMISSIONS.md package-source-read-only
    rule). Without this bootstrap, the first ``prepare_compiled_support``
    invocation tries to clone mathlib into ``.lake/packages/mathlib`` and
    fails with EROFS.

    Mirror approach: hardlink each top-level package source tree from
    worker → supervisor. Hardlinks share inodes (no disk overhead — on a
    typical project, on the order of hundreds of MB of metadata vs a
    multi-GB worker tree). Prewarmed package-local ``.lake/config`` closures
    are mirrored as well: Lake reads them while resolving the pinned package,
    and the sandbox intentionally forbids creating them at run time.

    S2 (live-run incident 2026-06-26): per-package ``.lake/build`` (the
    prebuilt package OLEANS — e.g. mathlib's) is now ALSO hardlinked.
    Previously the whole per-package ``.lake/`` was skipped, so a fresh
    supervisor workspace had package SOURCE but no oleans; under the
    ``lake_compiler`` bwrap ``.lake/packages/`` is read-only, so the first
    ``prepare_compiled_support`` could not build the missing oleans and
    fast-failed with EROFS and empty stderr (the incident's "11 frontier
    nodes un-fingerprinted → diverge"). Sharing the read-only package
    oleans by inode makes the workspace immediately buildable. If a package
    has source but NO ``.lake/build`` oleans on the worker side either, we
    fail loud with an actionable message rather than deferring to a later
    empty-stderr EROFS.

    Idempotent and crash-resumable: every package tree is revisited and only
    missing entries are populated. This matters because a process can stop
    after creating a package directory but before completing its contents.

    Git package checkouts may contain symlinks (including intentionally broken
    documentation links whose generated target is absent). Preserve those
    links without dereferencing them. Absolute links and relative links that
    resolve outside their package root are rejected so package materialization
    cannot create a supervisor-workspace escape.
    """
    worker_packages = worker_repo / ".lake" / "packages"
    supervisor_packages = supervisor_repo / ".lake" / "packages"
    stats = {"packages_linked": 0, "files_linked": 0, "files_copied": 0}
    if not worker_packages.is_dir():
        return stats
    supervisor_packages.mkdir(parents=True, exist_ok=True)
    for src_pkg in sorted(worker_packages.iterdir()):
        if not src_pkg.is_dir():
            continue
        dst_pkg = supervisor_packages / src_pkg.name
        package_was_present = dst_pkg.is_dir()
        if os.path.lexists(dst_pkg) and not package_was_present:
            raise RuntimeError(
                f"supervisor package destination is not a directory: {dst_pkg}"
            )

        def _preserve_package_symlink(src_link: Path, dst_link: Path) -> None:
            target = os.readlink(src_link)
            target_path = Path(target)
            if target_path.is_absolute():
                raise RuntimeError(
                    f"absolute symlink in lake package {src_pkg.name!r}: "
                    f"{src_link} -> {target}"
                )
            resolved_target = (src_link.parent / target_path).resolve(strict=False)
            package_root = src_pkg.resolve()
            if not resolved_target.is_relative_to(package_root):
                raise RuntimeError(
                    f"escaping symlink in lake package {src_pkg.name!r}: "
                    f"{src_link} -> {target}"
                )
            if os.path.lexists(dst_link):
                if dst_link.is_symlink() and os.readlink(dst_link) == target:
                    return
                raise RuntimeError(
                    f"conflicting supervisor package entry: {dst_link}"
                )
            dst_link.parent.mkdir(parents=True, exist_ok=True)
            os.symlink(target, dst_link)

        def _link_tree(src_root: Path, *, skip_dotlake: bool) -> None:
            for src_dirpath, dirnames, filenames in os.walk(src_root):
                # In the source pass, skip per-package `.lake/` (build +
                # config). The prewarmed build and config closures are linked
                # separately below; other package-local Lake state stays
                # absent.
                if skip_dotlake and ".lake" in dirnames:
                    dirnames.remove(".lake")
                rel = Path(src_dirpath).relative_to(src_pkg)
                dst_dirpath = dst_pkg / rel if rel != Path(".") else dst_pkg
                dst_dirpath.mkdir(parents=True, exist_ok=True)
                # os.walk(followlinks=False) still reports symlinked
                # directories in dirnames. Preserve them explicitly and keep
                # the walker from turning them into ordinary directories.
                for name in list(dirnames):
                    src_dir = Path(src_dirpath) / name
                    if not src_dir.is_symlink():
                        continue
                    _preserve_package_symlink(src_dir, dst_dirpath / name)
                    dirnames.remove(name)
                for name in filenames:
                    src_file = Path(src_dirpath) / name
                    dst_file = dst_dirpath / name
                    if src_file.is_symlink():
                        _preserve_package_symlink(src_file, dst_file)
                        continue
                    if os.path.lexists(dst_file):
                        continue
                    try:
                        os.link(src_file, dst_file)
                        stats["files_linked"] += 1
                    except OSError:
                        # Cross-device, perm denied, etc. — fall back to copy.
                        shutil.copy2(src_file, dst_file)
                        stats["files_copied"] += 1

        _link_tree(src_pkg, skip_dotlake=True)
        # S2: share all prebuilt package oleans (read-only) so the fresh
        # supervisor workspace is immediately buildable under the read-only
        # `.lake/packages/` bwrap. A Lake git dependency may name a `subDir`;
        # in that case its build directory is nested there rather than at the
        # checkout root (for example `aeneas/backends/lean/.lake/build`).
        src_builds: list[Path] = []
        src_configs: list[Path] = []
        for current, dirnames, _filenames in os.walk(src_pkg):
            dirnames[:] = [
                name
                for name in dirnames
                if name != ".git" and not (Path(current) / name).is_symlink()
            ]
            if ".lake" not in dirnames:
                continue
            src_build = Path(current) / ".lake" / "build"
            src_config = Path(current) / ".lake" / "config"
            if src_build.is_dir() and any(src_build.iterdir()):
                src_builds.append(src_build)
            if src_config.is_dir() and any(src_config.iterdir()):
                src_configs.append(src_config)
            # Build/config roots cannot contain another package-local `.lake`
            # root, and cache/temp content is deliberately not mirrored.
            dirnames.remove(".lake")
        for src_config in src_configs:
            _link_tree(src_config, skip_dotlake=False)
        for src_build in src_builds:
            _link_tree(src_build, skip_dotlake=False)
        if not src_builds and src_pkg.name not in _OLEAN_OPTIONAL_PACKAGES:
            # Loud, actionable surface for the EROFS-with-empty-stderr trap:
            # source present but no prebuilt oleans to share. We warn rather
            # than raise because some packages legitimately ship no build
            # outputs; a genuinely missing mathlib olean still surfaces here
            # by name instead of as an opaque downstream EROFS.
            #
            # Scope of the predicted failure, stated precisely because the
            # earlier wording overstated it: the lake_compiler bwrap DOES bind
            # every `<pkg>/.lake/build` and `<pkg>/.lake/config` read-write
            # (see `sandbox.py:_repo_writable_paths`, role "lake_compiler"), so
            # a trusted-role build can still produce missing package oleans in
            # place — what it cannot do is fetch or clone package SOURCE. The
            # role that would genuinely EROFS here is the untrusted `grunt`,
            # which is deliberately denied those per-package build binds.
            print(
                f"trellis: WARNING supervisor lake bootstrap — package "
                f"{src_pkg.name!r} has source but no prebuilt oleans at "
                f"any package-local .lake/build under {src_pkg}. Any grunt "
                f"build whose import closure reaches this package will fail "
                f"with EROFS (the grunt bwrap withholds per-package "
                f"'.lake/build'); trusted roles will silently rebuild it. "
                f"Re-run the worker prewarm ('lake exe cache get', plus "
                f"'lake build {src_pkg.name}' for tooling-only deps absent "
                f"from that cache) before syncing the supervisor workspace.",
                file=sys.stderr,
            )
        if not package_was_present:
            stats["packages_linked"] += 1
    return stats


def sync_supervisor_workspace(worker_repo: Path) -> Dict[str, Any]:
    from trellis.checking import write_scripts

    worker_repo = worker_repo.resolve()
    paths = _paths(worker_repo)
    paths.root.mkdir(parents=True, exist_ok=True)
    paths.repo.mkdir(parents=True, exist_ok=True)
    paths.home.mkdir(parents=True, exist_ok=True)
    paths.cache.mkdir(parents=True, exist_ok=True)
    sync_stats = _sync_repo_tree(worker_repo, paths.repo)
    package_stats = _ensure_supervisor_lake_packages(worker_repo, paths.repo)
    marker_payload = _write_marker(worker_repo, paths)
    write_scripts(paths.repo, project_state_dir_for_repo(paths.repo))
    return {
        "ok": True,
        "worker_repo_path": str(worker_repo),
        "authoritative_repo_path": str(paths.repo),
        "supervisor_home": str(paths.home),
        "supervisor_cache": str(paths.cache),
        "marker_path": str(paths.marker),
        "sync": sync_stats,
        "lake_packages": package_stats,
        "marker": marker_payload,
    }


def authoritative_env_for_repo(repo: Path) -> dict[str, str]:
    marker_path = supervisor_workspace_marker_path(repo.resolve())
    if not marker_path.is_file():
        return {}
    try:
        payload = json.loads(marker_path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    home = Path(str(payload.get("supervisor_home", "") or "")).expanduser()
    cache = Path(str(payload.get("supervisor_cache", "") or "")).expanduser()
    if not home or not cache:
        return {}
    home.mkdir(parents=True, exist_ok=True)
    cache.mkdir(parents=True, exist_ok=True)
    env = {
        "HOME": str(home.resolve()),
        "XDG_CACHE_HOME": str(cache.resolve()),
    }
    elan_home = os.environ.get("ELAN_HOME")
    if elan_home:
        env["ELAN_HOME"] = elan_home
    return env
