"""Supervisor-owned authoritative workspace helpers."""

from __future__ import annotations

import errno
import json
import os
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict

from trellis.project_paths import (
    project_state_dir_for_repo,
    supervisor_root_dir,
    supervisor_workspace_cache_path,
    supervisor_workspace_home_path,
    supervisor_workspace_marker_path,
    supervisor_workspace_repo_path,
)


_EXCLUDED_NAMES = {
    ".git",
    ".lake",
    ".trellis",
    ".trellis-history",
    ".pytest_cache",
    ".viewer",
    "__pycache__",
    "node_modules",
    "target",
}


@dataclass(frozen=True)
class SupervisorWorkspacePaths:
    root: Path
    repo: Path
    home: Path
    cache: Path
    marker: Path


def _paths(worker_repo: Path) -> SupervisorWorkspacePaths:
    worker_repo = worker_repo.resolve()
    repo = supervisor_workspace_repo_path(worker_repo).resolve()
    return SupervisorWorkspacePaths(
        root=supervisor_root_dir(worker_repo).resolve(),
        repo=repo,
        home=supervisor_workspace_home_path(worker_repo).resolve(),
        cache=supervisor_workspace_cache_path(worker_repo).resolve(),
        marker=supervisor_workspace_marker_path(repo).resolve(),
    )


def authoritative_repo_path(worker_repo: Path) -> Path:
    return _paths(worker_repo.resolve()).repo


def _skip_name(name: str) -> bool:
    return name in _EXCLUDED_NAMES or name.startswith(".tmp")


def _copy_file_if_needed(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    try:
        src_stat = src.stat()
    except OSError:
        return
    if dst.exists():
        try:
            dst_stat = dst.stat()
            if (
                dst_stat.st_size == src_stat.st_size
                and dst_stat.st_mtime_ns == src_stat.st_mtime_ns
            ):
                return
        except OSError:
            pass
    # `shutil.copy2` writes the content via group-writable access (works for
    # supervisor → burst-user:supervisor-group files), then `copystat` calls
    # `os.chmod` which requires *owning* the dest. Worker-burst-created
    # tablet files (INDEX.md, README.md regenerated by `sync-tablet-support`
    # inside the bwrap sandbox) are owned by the burst user; chmod from the
    # supervisor user raises EPERM. The content copy already succeeded
    # by that point — we only lose mtime preservation, which is a perf hint
    # for the size+mtime skip-fast-path above (next call will re-copy
    # unnecessarily but correctness is unaffected). Treat EPERM as success.
    try:
        shutil.copy2(src, dst)
        # Normalise group-read perms after copy. The verifier lane runs as
        # the burst user (member of the supervisor's group) and must be
        # able to read every Tablet file; some agent backends produce files
        # with mode 0o600 (e.g. mktemp+rename patterns that bypass umask),
        # and `shutil.copy2` preserves the source mode while assigning the
        # supervisor's uid to the dst. Without this chmod, a
        # mode-600 supervisor-owned file is owner-only, denying the
        # verifier read access. Mode 0o664 mirrors the rest of the tablet
        # — owner+group rw, world r — and lets both worker writes (via the
        # shared supervisor group) and verifier reads succeed.
        try:
            os.chmod(dst, 0o664)
        except OSError as chmod_exc:
            # When dst is owned by the burst user (auto-managed
            # INDEX.md/README.md case), supervisor lacks chmod rights.
            # The file already has whatever perms the worker wrote, which
            # is fine — same EPERM-tolerance as copystat above.
            if chmod_exc.errno != errno.EPERM:
                raise
    except OSError as exc:
        if exc.errno != errno.EPERM:
            raise


def propagate_tablet_back_to_worker(
    supervisor_repo: Path, worker_repo: Path
) -> Dict[str, int]:
    """Copy kernel-mutated `Tablet/` files from supervisor → worker.

    Two kernel-side processes write to the supervisor's `Tablet/` directory
    during a worker request lifecycle:
      1. `sync_tablet_support` (`atomic_actions/tablet_support.py`) regenerates
         `Tablet/INDEX.md`, `Tablet/README.md`, `Tablet/header.tex` from the
         current kernel state.
      2. `ensure_preamble_import_for_orphan` (`kernel/src/filespec.rs:232`,
         invoked from `validate_worker_result`) injects `import Tablet.Preamble`
         into orphan node `.lean` files.
    Both modify the supervisor repo (the authoritative_repo the kernel sees).
    Without this back-propagation, the worker repo (which
    `git_checkpoint_hook.py` actually commits) silently diverges from the
    kernel's view, with two destructive consequences:

      a. git HEAD ends up missing the kernel's mutations → after a checkpoint
         the kernel-blessed state is lost from history.
      b. The validator's `before_snapshot` (captured from supervisor) doesn't
         match what's on the worker repo's disk for these auto-managed files,
         so the validator reports phantom modifications — the worker is
         rejected for changes it never made and cannot revert from inside its
         Easy-mode scope. Loop is unrecoverable.

    Copies all `Tablet/*.lean`, `Tablet/*.tex`, and the three auto-managed
    docs (`INDEX.md`, `README.md`, `header.tex`) from supervisor → worker.
    Idempotent (size/mtime check) and safe to call after every Valid/Invalid
    worker normalization.
    """
    src_tablet = (supervisor_repo / "Tablet").resolve()
    dst_tablet = (worker_repo / "Tablet").resolve()
    copied = 0
    if not src_tablet.is_dir() or not dst_tablet.is_dir():
        return {"copied_files": 0}
    for src in src_tablet.iterdir():
        if not src.is_file():
            continue
        # Auto-managed by sync_tablet_support: regenerated each prep.
        is_managed_doc = src.name in {"INDEX.md", "README.md", "header.tex"}
        # Tablet node content: subject to ensure_preamble_import_for_orphan.
        is_node_file = src.suffix in {".lean", ".tex"}
        if not (is_managed_doc or is_node_file):
            continue
        dst = dst_tablet / src.name
        before_exists = dst.exists()
        before_mtime = dst.stat().st_mtime_ns if before_exists else None
        _copy_file_if_needed(src, dst)
        if not before_exists or (
            dst.exists() and dst.stat().st_mtime_ns != before_mtime
        ):
            copied += 1
    return {"copied_files": copied}


def _sync_repo_tree(worker_repo: Path, supervisor_repo: Path) -> Dict[str, int]:
    desired_files: set[Path] = set()
    desired_dirs: set[Path] = {Path(".")}
    copied_files = 0

    for current, dirnames, filenames in os.walk(worker_repo):
        current_path = Path(current)
        rel_dir = current_path.relative_to(worker_repo)
        dirnames[:] = [
            name
            for name in dirnames
            if not _skip_name(name)
        ]
        desired_dirs.add(rel_dir)
        target_dir = supervisor_repo / rel_dir if rel_dir != Path(".") else supervisor_repo
        target_dir.mkdir(parents=True, exist_ok=True)
        for name in filenames:
            if _skip_name(name):
                continue
            rel_path = rel_dir / name if rel_dir != Path(".") else Path(name)
            desired_files.add(rel_path)
            before = (supervisor_repo / rel_path).exists()
            _copy_file_if_needed(worker_repo / rel_path, supervisor_repo / rel_path)
            if not before or (supervisor_repo / rel_path).exists():
                copied_files += 1

    preserved_roots = {Path(".lake"), Path(".trellis"), Path(".trellis-supervisor.json")}
    for current, dirnames, filenames in os.walk(supervisor_repo, topdown=False):
        current_path = Path(current)
        rel_dir = current_path.relative_to(supervisor_repo)
        if rel_dir == Path("."):
            continue
        if rel_dir in preserved_roots or any(
            part in {".lake", ".trellis"} for part in rel_dir.parts
        ):
            continue
        for name in filenames:
            rel_path = rel_dir / name
            if rel_path in desired_files:
                continue
            (supervisor_repo / rel_path).unlink(missing_ok=True)
        for name in dirnames:
            rel_path = rel_dir / name
            if rel_path in desired_dirs:
                continue
            full = supervisor_repo / rel_path
            if rel_path in preserved_roots or name in {".lake", ".trellis"}:
                continue
            shutil.rmtree(full, ignore_errors=True)
        if rel_dir not in desired_dirs:
            shutil.rmtree(current_path, ignore_errors=True)

    return {
        "copied_files": copied_files,
        "tracked_files": len(desired_files),
        "tracked_dirs": len(desired_dirs),
    }


def _write_marker(worker_repo: Path, paths: SupervisorWorkspacePaths) -> Dict[str, Any]:
    payload = {
        "worker_repo_path": str(worker_repo.resolve()),
        "supervisor_repo_path": str(paths.repo),
        "supervisor_home": str(paths.home),
        "supervisor_cache": str(paths.cache),
    }
    paths.marker.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return payload


def _ensure_supervisor_lake_packages(
    worker_repo: Path, supervisor_repo: Path
) -> Dict[str, int]:
    """One-time hardlink of ``<worker>/.lake/packages`` → ``<supervisor>/.lake/packages``.

    Worker-side packages are populated by ``setup_repo.sh``'s burst-user
    prewarm path (``lake exe cache get`` runs as the burst user outside
    the lake_compiler bwrap). The supervisor workspace's ``_sync_repo_tree``
    excludes ``.lake/`` entirely so each role keeps its own build outputs,
    but that means the supervisor repo has NO package source on first sync.

    With ``--with-checker-rpc`` mode, lake invocations route through the
    ``lake_compiler`` bwrap, whose writable allowlist excludes
    ``.lake/packages/`` by design (PERMISSIONS.md package-source-read-only
    rule). Without this bootstrap, the first ``prepare_compiled_support``
    invocation tries to clone mathlib into ``.lake/packages/mathlib`` and
    fails with EROFS.

    Mirror approach: hardlink each top-level package source tree from
    worker → supervisor. Hardlinks share inodes (no disk overhead — on a
    typical project, on the order of hundreds of MB of metadata vs a
    multi-GB worker tree). Per-package
    ``.lake/`` (build outputs + config) is intentionally skipped — each
    role keeps its own writable per-package ``.lake/{build,config}``.

    Idempotent: short-circuits when the supervisor packages dir already
    has at least one entry.
    """
    worker_packages = worker_repo / ".lake" / "packages"
    supervisor_packages = supervisor_repo / ".lake" / "packages"
    stats = {"packages_linked": 0, "files_linked": 0, "files_copied": 0}
    if not worker_packages.is_dir():
        return stats
    if supervisor_packages.is_dir() and any(supervisor_packages.iterdir()):
        return stats
    supervisor_packages.mkdir(parents=True, exist_ok=True)
    for src_pkg in sorted(worker_packages.iterdir()):
        if not src_pkg.is_dir():
            continue
        dst_pkg = supervisor_packages / src_pkg.name
        if dst_pkg.exists():
            continue
        for src_dirpath, dirnames, filenames in os.walk(src_pkg):
            # Skip per-package `.lake/` entirely (build outputs + config
            # are role-specific). Mutate dirnames in place so os.walk
            # doesn't descend.
            if ".lake" in dirnames:
                dirnames.remove(".lake")
            rel = Path(src_dirpath).relative_to(src_pkg)
            dst_dirpath = dst_pkg / rel if rel != Path(".") else dst_pkg
            dst_dirpath.mkdir(parents=True, exist_ok=True)
            for name in filenames:
                src_file = Path(src_dirpath) / name
                dst_file = dst_dirpath / name
                if dst_file.exists():
                    continue
                try:
                    os.link(src_file, dst_file)
                    stats["files_linked"] += 1
                except OSError:
                    # Cross-device, perm denied, etc. — fall back to copy.
                    shutil.copy2(src_file, dst_file)
                    stats["files_copied"] += 1
        stats["packages_linked"] += 1
    return stats


def sync_supervisor_workspace(worker_repo: Path) -> Dict[str, Any]:
    from trellis.checking import write_scripts

    worker_repo = worker_repo.resolve()
    paths = _paths(worker_repo)
    paths.root.mkdir(parents=True, exist_ok=True)
    paths.repo.mkdir(parents=True, exist_ok=True)
    paths.home.mkdir(parents=True, exist_ok=True)
    paths.cache.mkdir(parents=True, exist_ok=True)
    sync_stats = _sync_repo_tree(worker_repo, paths.repo)
    package_stats = _ensure_supervisor_lake_packages(worker_repo, paths.repo)
    marker_payload = _write_marker(worker_repo, paths)
    write_scripts(paths.repo, project_state_dir_for_repo(paths.repo))
    return {
        "ok": True,
        "worker_repo_path": str(worker_repo),
        "authoritative_repo_path": str(paths.repo),
        "supervisor_home": str(paths.home),
        "supervisor_cache": str(paths.cache),
        "marker_path": str(paths.marker),
        "sync": sync_stats,
        "lake_packages": package_stats,
        "marker": marker_payload,
    }


def authoritative_env_for_repo(repo: Path) -> dict[str, str]:
    marker_path = supervisor_workspace_marker_path(repo.resolve())
    if not marker_path.is_file():
        return {}
    try:
        payload = json.loads(marker_path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    home = Path(str(payload.get("supervisor_home", "") or "")).expanduser()
    cache = Path(str(payload.get("supervisor_cache", "") or "")).expanduser()
    if not home or not cache:
        return {}
    home.mkdir(parents=True, exist_ok=True)
    cache.mkdir(parents=True, exist_ok=True)
    env = {
        "HOME": str(home.resolve()),
        "XDG_CACHE_HOME": str(cache.resolve()),
    }
    elan_home = os.environ.get("ELAN_HOME")
    if elan_home:
        env["ELAN_HOME"] = elan_home
    return env
